# Generated by Django 5.1.6 on 2025-05-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0003_article_image_alter_article_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="image",
            new_name="header_image",
        ),
    ]
