# Generated by Django 5.1.6 on 2025-05-12 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
        ("wiki", "0004_rename_image_article_header_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiki_articles",
                to="user_management.profile",
            ),
        ),
    ]
