# Generated by Django 5.1.6 on 2025-05-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="header_image",
            field=models.ImageField(
                default="images/placeholder.png", null=True, upload_to="blog/images/"
            ),
        ),
    ]
