# Generated by Django 5.1.6 on 2025-03-13 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "productTypeID",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        default="Some variety of items sold in this merch store."
                    ),
                ),
            ],
            options={
                "verbose_name": "ProductType",
                "verbose_name_plural": "ProductTypes",
                "ordering": ["name"],
                "unique_together": {("name",)},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "productID",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "description",
                    models.TextField(default="A buyable item of this merch store."),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ProductType",
                        to="merchstore.producttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["name"],
                "unique_together": {("name",)},
            },
        ),
    ]
