# Generated by Django 5.1.6 on 2025-05-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchstore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("On Sale", "On Sale"),
                    ("Out Of Stock", "Out Of Stock"),
                ],
                default="Available",
                max_length=12,
            ),
        ),
    ]
