# Generated by Django 5.1.6 on 2025-03-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(),
        ),
    ]
