# Generated by Django 5.1.6 on 2025-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='productID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='producttype',
            name='productTypeID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='A buyable item of this merch store.'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(default='Some variety of items sold in this merch store.'),
        ),
    ]
