# Generated by Django 5.1.6 on 2025-04-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0003_product_status_product_stock_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
