# Generated by Django 5.1.6 on 2025-03-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0003_alter_producttype_producttypeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='productTypeID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
